### ISSUE TITLE
Intel(R) Core(TM) i9-14900K

### ISSUE THREAD

**Issue by valentin-barbotin** [cyring/CoreFreq#514]
Microcode 0x129
Z790 Aorus Elite AX (rev 1.1) with FJh BIOS version
https://www.aorus.com/motherboards/Z790-AORUS-ELITE-AX-rev-1x/Support
BIOS Pictures : https://drive.google.com/drive/folders/1QK8Sr8AuSifU_IauHk4uHpnr5zDtK9JB?usp=sharing

![allturbo](https://github.com/user-attachments/assets/96a98352-c623-40ce-b368-6451a9406c36)
![turborandom](https://github.com/user-attachments/assets/051970b3-eb08-4ecf-9a79-636a6b872c27)
![atomicburn](https://github.com/user-attachments/assets/974f2bf2-686a-4583-9441-982505b498fd)
![events](https://github.com/user-attachments/assets/8c726400-2024-464a-b1ac-c682ac581549)
![memory](https://github.com/user-attachments/assets/e88f64ed-6310-49ab-a288-f6039cbdfca9)
![power2](https://github.com/user-attachments/assets/9d83115b-1444-4be5-92ec-cc63d5863313)
![power1](https://github.com/user-attachments/assets/22d27457-2052-4591-a0f7-5eb4d2d316a3)
![PC](https://github.com/user-attachments/assets/e5c24af0-e570-4b3e-a040-9ae4f6003123)
![pm2](https://github.com/user-attachments/assets/9ba0df34-4fd7-4205-82a2-fd8c147a8bc2)
![pm1](https://github.com/user-attachments/assets/e17676b5-0f29-4a74-affc-1c171861bba5)
![tech2](https://github.com/user-attachments/assets/0bc0aa6b-9aa2-44cb-b125-6adc565ae8d1)
![tech1](https://github.com/user-attachments/assets/0e762fe3-c233-4cd8-9c90-21fc3e3fc3b1)
![ISA](https://github.com/user-attachments/assets/c3c3d8a3-3e1c-4afd-a168-9927c383a842)
![feature6](https://github.com/user-attachments/assets/49409fb9-cfbc-413c-a326-dd10765914b9)
![feature5](https://github.com/user-attachments/assets/4cddadda-2bb5-4881-8506-b049eca8e32f)
![feature4](https://github.com/user-attachments/assets/295bf782-eb3f-48ab-98ec-5ec52f99389a)
![feature3](https://github.com/user-attachments/assets/cc76917a-bc7e-4612-af0c-cd2520667f25)
![feature2](https://github.com/user-attachments/assets/1e514fa5-a8c7-4816-9bef-8c9bd3e84440)
![features1](https://github.com/user-attachments/assets/c9f49098-0df1-43c6-80cb-b352c5a21858)
![topology](https://github.com/user-attachments/assets/ffd34d3f-6fc1-4051-bdb3-c82a723dcea7)
![idle4](https://github.com/user-attachments/assets/0f472de4-7506-4445-8077-a2532f409e40)
![idle3](https://github.com/user-attachments/assets/9839630d-2cca-45a7-bfdd-996f98e48001)

**Comment by cyring** [comment]
_CoreFreq_ looks great with your processor.

**Thank you**

* You should try enabling CC6 and MC6 for further C-States and less consumed energy

* HWP Highest ratio of `73` has not been computed into a frequency.  

   Which _CoreFreq_ version are you using ?
   If not greater than `1.98.4`, can you update _CoreFreq_ and check again for this issue ?
   Also try to output in text using `corefreq-cli -z` to see if HWP frequencies are all printed or not ?

**Comment by cyring** [comment]
Can you start or change for `Experimental` in `Settings` ?
Once enabled please find option `ODCM`, On Demand Clock Modulation, in "Power" window.
Activate this option and set the percent in the `BIAS HINT`
The processor frequency, when stressed, should reduce as much as the percent set in the bias.
Just deactivate `ODCM` to restore frequency to its nominal.

If the `ODCM` test succeed then I will mark as permanent for Raptor Lake in next CoreFreq version.

**Comment by cyring** [comment]
> * HWP Highest ratio of `73` has not been computed into a frequency.
>   Which _CoreFreq_ version are you using ?
>   If not greater than `1.98.4`, can you update _CoreFreq_ and check again for this issue ?
>   Also try to output in text using `corefreq-cli -z` to see if HWP frequencies are all printed or not ?

This UI issue is now fixed in commit cb55c1b72686772c1cec104ea269ef8f8cfd82c8

**Comment by valentin-barbotin** [comment]
Corefreq version was 1.98.0, now using 1.98.4

corefreq-cli -z output :
```
|- Hardware-Controlled Performance States                        HWP       < ON>
   |- Capabilities     Lowest      Efficient     Guaranteed        Highest      
   |- CPU #0      99.60 (  1)  1792.73 ( 18)  4083.45 ( 41)     0.00 ( 73)      
   |- CPU #1      99.60 (  1)  1792.73 ( 18)  4083.45 ( 41)     0.00 ( 73)      
   |- CPU #2      99.59 (  1)  1792.58 ( 18)  4083.09 ( 41)     0.00 ( 73)      
   |- CPU #3      99.59 (  1)  1792.63 ( 18)  4083.20 ( 41)     0.00 ( 73)      
   |- CPU #4      99.59 (  1)  1792.60 ( 18)  4083.14 ( 41)     0.00 ( 73)      
   |- CPU #5      99.59 (  1)  1792.62 ( 18)  4083.20 ( 41)     0.00 ( 73)      
   |- CPU #6      99.59 (  1)  1792.63 ( 18)  4083.20 ( 41)     0.00 ( 73)      
   |- CPU #7      99.59 (  1)  1792.67 ( 18)  4083.30 ( 41)     0.00 ( 73)      
   |- CPU #8      99.60 (  1)  1792.73 ( 18)  4083.45 ( 41)     0.00 ( 77)      
   |- CPU #9      99.59 (  1)  1792.69 ( 18)  4083.36 ( 41)     0.00 ( 77)      
   |- CPU #10     99.60 (  1)  1792.73 ( 18)  4083.45 ( 41)     0.00 ( 77)      
   |- CPU #11     99.60 (  1)  1792.73 ( 18)  4083.45 ( 41)     0.00 ( 77)      
   |- CPU #12     99.60 (  1)  1792.84 ( 18)  4083.68 ( 41)     0.00 ( 73)      
   |- CPU #13     99.60 (  1)  1792.81 ( 18)  4083.62 ( 41)     0.00 ( 73)      
   |- CPU #14     99.60 (  1)  1792.73 ( 18)  4083.45 ( 41)     0.00 ( 73)      
   |- CPU #15     99.60 (  1)  1792.73 ( 18)  4083.45 ( 41)     0.00 ( 73)      
   |- CPU #16     99.60 (  1)  1394.35 ( 14)  2390.31 ( 24)  4382.23 ( 44)      
   |- CPU #17     99.60 (  1)  1394.35 ( 14)  2390.32 ( 24)  4382.25 ( 44)      
   |- CPU #18     99.60 (  1)  1394.38 ( 14)  2390.37 ( 24)  4382.34 ( 44)      
   |- CPU #19     99.59 (  1)  1394.33 ( 14)  2390.27 ( 24)  4382.17 ( 44)      
   |- CPU #20     99.60 (  1)  1394.35 ( 14)  2390.31 ( 24)  4382.24 ( 44)      
   |- CPU #21     99.60 (  1)  1394.35 ( 14)  2390.31 ( 24)  4382.24 ( 44)      
   |- CPU #22     99.60 (  1)  1394.36 ( 14)  2390.33 ( 24)  4382.27 ( 44)      
   |- CPU #23     99.60 (  1)  1394.36 ( 14)  2390.34 ( 24)  4382.28 ( 44)      
   |- CPU #24     99.60 (  1)  1394.35 ( 14)  2390.32 ( 24)  4382.25 ( 44)      
   |- CPU #25     99.60 (  1)  1394.35 ( 14)  2390.31 ( 24)  4382.24 ( 44)      
   |- CPU #26     99.60 (  1)  1394.45 ( 14)  2390.49 ( 24)  4382.56 ( 44)      
   |- CPU #27     99.60 (  1)  1394.36 ( 14)  2390.33 ( 24)  4382.26 ( 44)      
   |- CPU #28     99.60 (  1)  1394.35 ( 14)  2390.31 ( 24)  4382.24 ( 44)      
   |- CPU #29     99.60 (  1)  1394.35 ( 14)  2390.32 ( 24)  4382.25 ( 44)      
   |- CPU #30     99.60 (  1)  1394.34 ( 14)  2390.30 ( 24)  4382.21 ( 44)      
   |- CPU #31     99.60 (  1)  1394.35 ( 14)  2390.32 ( 24)  4382.25 ( 44)      

```


[corefreq_screens_odcm.zip](https://github.com/user-attachments/files/17723900/corefreq_screens_odcm.zip)

**Comment by cyring** [comment]
> Corefreq version was 1.98.0, now using 1.98.4
* Thanks for your return.
* For your testings, a fix is available since commit cb55c1b72686772c1cec104ea269ef8f8cfd82c8

----

ODCM can be safely enable/disable
Per `12.5%` step and apparently only on Ecores whereas Pcores remain at `7 MHz`
ODCM feature will be marked as no more experimental in next release.

**Comment by valentin-barbotin** [comment]
![image](https://github.com/user-attachments/assets/c9abf998-661f-4472-aa89-5698e39ea018)

I am now using version 1.98.5, thanks to the package maintainer
I haven't rebooted yet but I have reloaded the service and the module and it seems the problem still persists
Here is the proof with the version of CoreFreq displayed

**Comment by cyring** [comment]
> I am now using version 1.98.5, thanks to the package maintainer I haven't rebooted yet but I have reloaded the service and the module and it seems the problem still persists Here is the proof with the version of CoreFreq displayed

Is it possible that you try directly from the repository rather than a package ?
Make sure to unload/uninstall all previous versions before
```sh
git clone -b develop https://github.com/cyring/CoreFreq.git

cd CoreFreq
make
```
* As root
```
insmod build/corefreqk.ko
./build/corefreqd
```
* As User
```
./build/corefreq-cli
```

**Comment by cyring** [comment]
@valentin-barbotin 
Sorry I should have tell you that fix is available since two commits above master
So as shown just above, you have to pull code from the [develop branch](https://github.com/cyring/CoreFreq/commits/develop)

**Comment by cyring** [comment]
> It's better with right commit :)

Thank you very much

**Comment by cyring** [comment]
For production
